#!/bin/bash

cat > /var/www/.env << EOF
APP_NAME=PiezoDashboard
APP_ENV=${APP_ENV}
APP_KEY=${APP_KEY}
APP_DEBUG=${APP_DEBUG}
APP_URL=${APP_URL}
APP_TIMEZONE=UTC
APP_LOCALE=en
APP_FALLBACK_LOCALE=en

LOG_CHANNEL=stack
LOG_STACK=single
LOG_LEVEL=debug

DB_CONNECTION=mysql
DB_HOST=${DB_HOST}
DB_PORT=${DB_PORT}
DB_DATABASE=${DB_DATABASE}
DB_USERNAME=${DB_USERNAME}
DB_PASSWORD=${DB_PASSWORD}

MYSQL_ATTR_SSL_CA=${MYSQL_ATTR_SSL_CA}

SESSION_DRIVER=database
SESSION_LIFETIME=120
CACHE_STORE=database
QUEUE_CONNECTION=database

MQTT_HOST=${MQTT_HOST}
MQTT_PORT=${MQTT_PORT}
MQTT_USERNAME=${MQTT_USERNAME}
MQTT_PASSWORD=${MQTT_PASSWORD}
MQTT_CLIENT_ID=${MQTT_CLIENT_ID}
MQTT_TLS=${MQTT_TLS}
MQTT_TLS_VERIFY_PEER=${MQTT_TLS_VERIFY_PEER}
MQTT_TLS_VERIFY_PEER_NAME=${MQTT_TLS_VERIFY_PEER_NAME}

ESP_API_KEY=${ESP_API_KEY}
BCRYPT_ROUNDS=12
EOF

php artisan config:clear
php artisan config:cache
php artisan migrate --force
php artisan db:seed --force
php artisan serve --host=0.0.0.0 --port=8000